"""BIST sembolleri · Yahoo Finance formatı (.IS suffix)"""

BIST_SYMBOLS = [
    # BIST 30
    "AKBNK", "ARCLK", "ASELS", "BIMAS", "DOAS", "DOHOL", "EKGYO", "ENKAI",
    "EREGL", "FROTO", "GARAN", "GUBRF", "HALKB", "HEKTS", "ISCTR", "KCHOL",
    "KOZAL", "KOZAA", "KRDMD", "MGROS", "PETKM", "PGSUS", "SAHOL", "SASA",
    "SISE", "TAVHL", "TCELL", "THYAO", "TKFEN", "TOASO", "TTKOM", "TUPRS",
    "VAKBN", "VESTL", "YKBNK",
    # BIST 100/200
    "ALARK", "ALBRK", "AEFES", "AGHOL", "AKCNS", "AKFGY", "AKGRT", "AKSA",
    "AKSEN", "ALKIM", "ALKA", "ANACM", "ANELE", "ANELT", "ANHYT", "ANSGR",
    "ARENA", "ARSAN", "ASUZU", "ATAGY", "ATEKS", "AVGYO", "AVHOL", "AVTUR",
    "AYDEM", "AYEN", "AYGAZ", "BAGFS", "BAKAB", "BALAT", "BANVT", "BASCM",
    "BASGZ", "BERA", "BEYAZ", "BFREN", "BIENY", "BIOEN", "BIZIM", "BJKAS",
    "BLCYT", "BMSTL", "BNTAS", "BOBET", "BOLUC", "BORSK", "BOSSA", "BRISA",
    "BRKO", "BRSAN", "BRYAT", "BSOKE", "BTCIM", "BUCIM", "BURCE", "BURVA",
    "BVSAN", "BYDNR", "CANTE", "CCOLA", "CELHA", "CEMAS", "CEMTS", "CEOEM",
    "CIMSA", "CLEBI", "CMBTN", "CMENT", "COSMO", "CRDFA", "CRFSA", "CUSAN",
    "DAGI", "DAGHL", "DAPGM", "DARDL", "DERHL", "DERIM", "DESA", "DESPC",
    "DEVA", "DGATE", "DGGYO", "DGKLB", "DITAS", "DMSAS", "DNISI", "DOBUR",
    "DOCO", "DOGUB", "DURDO", "DYOBY", "ECILC", "ECZYT", "EDATA", "EDIP",
    "EGEEN", "EGGUB", "EGPRO", "EGSER", "ELITE", "EMKEL", "EMNIS", "ENJSA",
    "ENTRA", "EPLAS", "ERBOS", "ERCB", "ERSU", "ESCAR", "ESCOM", "ESEN",
    "ETYAT", "EUHOL", "EUPWR", "EUREN", "EUYO", "FADE", "FENER", "FLAP",
    "FMIZP", "FONET", "FORMT", "FORTE", "FRIGO", "GARFA", "GEDIK", "GEDZA",
    "GENIL", "GENTS", "GEREL", "GESAN", "GIPTA", "GLBMD", "GLCVY", "GLRYH",
    "GLYHO", "GMTAS", "GOLTS", "GOODY", "GOZDE", "GRNYO", "GRSEL", "GRTRK",
    "GSDDE", "GSDHO", "GSRAY", "GWIND", "HATEK", "HATSN", "HDFGS", "HLGYO",
    "HTTBT", "HUBVC", "HURGZ", "ICBCT", "ICUGS", "IDGYO", "IEYHO", "IHEVA",
    "IHGZT", "IHLAS", "IHLGM", "IHYAY", "IMASM", "INDES", "INFO", "INGRM",
    "INTEM", "INVEO", "INVES", "IPEKE", "ISATR", "ISBIR", "ISBTR", "ISDMR",
    "ISFIN", "ISGSY", "ISGYO", "ISKPL", "ISMEN", "ISSEN", "ISYAT", "IZENR",
    "IZFAS", "IZINV", "IZMDC", "JANTS", "KAPLM", "KAREL", "KARSN", "KARTN",
    "KARYE", "KATMR", "KAYSE", "KBORU", "KCAER", "KENT", "KERVN", "KERVT",
    "KFEIN", "KIMMR", "KLGYO", "KLKIM", "KLMSN", "KLRHO", "KLSER", "KLSYN",
    "KMPUR", "KNFRT", "KONKA", "KONTR", "KONYA", "KOPOL", "KORDS", "KRGYO",
    "KRONT", "KRPLS", "KRSTL", "KRTEK", "KRVGD", "KSTUR", "KTLEV", "KTSKR",
    "KUTPO", "KUYAS", "KZBGY", "KZGYO", "LIDER", "LIDFA", "LINK", "LKMNH",
    "LMKDC", "LOGO", "LRSHO", "LUKSK", "LYDHO", "MAALT", "MACKO", "MAGEN",
    "MAKIM", "MAKTK", "MANAS", "MARBL", "MARKA", "MARTI", "MAVI", "MEDTR",
    "MEGAP", "MEGMT", "MEKAG", "MEPET", "MERCN", "MERKO", "METRO", "METUR",
    "MHRGY", "MIATK", "MIPAZ", "MMCAS", "MNDRS", "MNDTR", "MOBTL", "MPARK",
    "MRGYO", "MRSHL", "MSGYO", "MTRKS", "MTRYO", "MZHLD", "NATEN", "NETAS",
    "NIBAS", "NTGAZ", "NTHOL", "NUGYO", "NUHCM", "ODAS", "OFSYM", "ONCSM",
    "ORCAY", "ORGE", "ORMA", "OSMEN", "OSTIM", "OTKAR", "OYAKC", "OYLUM",
    "OYYAT", "OZKGY", "OZRDN", "OZSUB", "PAGYO", "PAMEL", "PAPIL", "PARSN",
    "PASEU", "PATEK", "PCILT", "PEKGY", "PENGD", "PENTA", "PETUN", "PINSU",
    "PKART", "PKENT", "PLTUR", "PNLSN", "PNSUT", "POLHO", "POLTK", "PRDGS",
    "PRKAB", "PRKME", "PRZMA", "PSDTC", "QUAGR", "RALYH", "RAYSG", "REEDR",
    "RGYAS", "RNPOL", "RODRG", "ROYAL", "RTALB", "RUBNS", "RYGYO", "RYSAS",
    "SAFKR", "SAMAT", "SANEL", "SANFM", "SANKO", "SARKY", "SAYAS", "SDTTR",
    "SEGYO", "SEKFK", "SEKUR", "SELEC", "SELGD", "SELVA", "SEYKM", "SILVR",
    "SKBNK", "SKTAS", "SKYLP", "SKYMD", "SMART", "SMRTG", "SNGYO", "SNICA",
    "SNKRN", "SNPAM", "SODSN", "SOKE", "SOKM", "SONME", "SRVGY", "SUMAS",
    "SUNTK", "SUWEN", "TARKM", "TATEN", "TATGD", "TAYGN", "TDGYO", "TEKTU",
    "TERA", "TETMT", "TEZOL", "TGSAS", "TKNSA", "TLMAN", "TMPOL", "TMSN",
    "TNZTP", "TRCAS", "TRGYO", "TRILC", "TSGYO", "TSKB", "TSPOR", "TTRAK",
    "TUCLK", "TUKAS", "TUREX", "TURGG", "TURSG", "UFUK", "ULAS", "ULKER",
    "ULUFA", "ULUSE", "ULUUN", "UNLU", "USAK", "UTPYA", "UZERB", "VAKFN",
    "VAKKO", "VANGD", "VBTYZ", "VERTU", "VERUS", "VESBE", "VKFYO", "VKGYO",
    "VKING", "YAPRK", "YATAS", "YAYLA", "YBTAS", "YESIL", "YEOTK", "YGGYO",
    "YGYO", "YKSLN", "YUNSA", "YYAPI", "YYLGD", "ZEDUR", "ZOREN", "ZRGYO",
]

def get_all():
    return BIST_SYMBOLS

def to_yf(sym):
    return sym if sym.endswith('.IS') else f"{sym}.IS"

def from_yf(sym):
    return sym.replace('.IS', '')
